"""
CSV Parser for PowerFactory Contingency Analysis Results

This module handles parsing of the Resultados.csv file generated by PowerFactory
contingency analysis to extract line loading information.

Author: AI Assistant
Date: 2024
"""

import pandas as pd
import numpy as np


def parse_contingency_results(csv_file_path='Resultados.csv'):
    """
    Parse the PowerFactory contingency analysis results CSV file.
    
    Based on the CSV structure discovered:
    - 813 consecutive "Max. loading in %" columns starting from column 13
    - Loading percentages are stored at the bottom of each column (last row)
    - Line names are mapped from the actual PowerFactory line names
    
    Args:
        csv_file_path (str): Path to the CSV file
        
    Returns:
        pandas.DataFrame: DataFrame with columns:
            - 'Linea': Line name
            - 'Max_Loading_Percent': Maximum loading percentage for this line
            - 'Critical_Line': Name of the line that causes this maximum loading
    """
    print(f"Parsing contingency results from {csv_file_path}...")
    
    try:
        # Read the CSV file
        df = pd.read_csv(csv_file_path, encoding='latin1', low_memory=False)
        print(f"CSV loaded successfully. Shape: {df.shape}")
        
        # Parse the data
        results = []
        
        # Find all "Max. loading in %" columns
        max_loading_cols = []
        for col_idx in range(df.shape[1]):
            header = df.iloc[0, col_idx]
            if isinstance(header, str) and "Max. loading in %" in header:
                max_loading_cols.append(col_idx)
        
        print(f"Debug: Found {len(max_loading_cols)} 'Max. loading in %' columns")
        
        # Extract loading percentages from each column and keep DIgSILENT element names
        for i, col_idx in enumerate(max_loading_cols):
            # Extract the maximum loading percentage from the last row
            max_loading = _extract_last_value(df, col_idx)
            
            if max_loading is not None:
                # Keep the DIgSILENT element name from the CSV column label, e.g. 'Line 05 - 06.11'
                # and normalize it to the base element name 'Line 05 - 06'
                col_label = str(df.columns[col_idx])
                line_name = _extract_base_line_name_from_column_label(col_label)
                
                results.append({
                    'Linea': line_name,
                    'Max_Loading_Percent': max_loading,
                    'Critical_Line': 'Unknown'  # Will be improved later
                })
        
        # Create DataFrame
        if results:
            result_df = pd.DataFrame(results)
            result_df = result_df.sort_values(by='Max_Loading_Percent', ascending=False).reset_index(drop=True)
            print(f"Successfully parsed {len(result_df)} lines with loading data.")
            print(f"Max loading found: {result_df['Max_Loading_Percent'].max():.2f}%")
            return result_df
        else:
            print("No valid loading data found.")
            return pd.DataFrame(columns=['Linea', 'Max_Loading_Percent', 'Critical_Line'])
            
    except Exception as e:
        print(f"Error parsing CSV file: {e}")
        return pd.DataFrame(columns=['Linea', 'Max_Loading_Percent', 'Critical_Line'])


def _extract_last_value(df, col_idx):
    """
    Extract the last non-"----" value from a column.
    
    Args:
        df (pandas.DataFrame): The DataFrame
        col_idx (int): Column index
        
    Returns:
        float or str or None: The last valid value, or None if not found
    """
    if col_idx >= df.shape[1]:
        return None
        
    # Get the data column (from row 2 onwards)
    data_column = df.iloc[2:, col_idx].values
    
    # Find the last non-"----" value
    for val in reversed(data_column):
        if val != '----' and val != '   ----' and not pd.isna(val):
            try:
                # Try to convert to float first
                return float(val)
            except (ValueError, TypeError):
                # If not numeric, return as string
                return str(val)
    
    return None


def _build_contingency_mapping(df):
    """
    Build a mapping from contingency numbers to line names.
    
    Args:
        df (pandas.DataFrame): The CSV DataFrame
        
    Returns:
        dict: Mapping from contingency number to line name
    """
    mapping = {}
    
    # Look for columns that contain line names (not "Max. loading in %" or "Contingency (max. loading)")
    for col_idx in range(df.shape[1]):
        header = df.iloc[0, col_idx]
        
        # Check if this looks like a line name column
        if (isinstance(header, str) and 
            'Line' in header and 
            'Max. loading in %' not in header and 
            'Contingency (max. loading)' not in header):
            
            # Extract line name
            line_name = _clean_line_name(header)
            
            # Get the contingency number from the last non-"----" value
            contingency_number = _extract_last_value(df, col_idx)
            
            if contingency_number is not None:
                try:
                    # Convert to integer if possible
                    contingency_num = int(float(contingency_number))
                    mapping[contingency_num] = line_name
                    print(f"Debug: Mapped contingency {contingency_num} -> {line_name}")
                except (ValueError, TypeError):
                    continue
    
    return mapping


def _find_contingency_number(df, max_loading_col_idx):
    """
    Find the contingency number for a given "Max. loading in %" column.
    
    Args:
        df (pandas.DataFrame): The CSV DataFrame
        max_loading_col_idx (int): Index of the "Max. loading in %" column
        
    Returns:
        int or None: The contingency number, or None if not found
    """
    # Look for the corresponding "Contingency (max. loading)" column
    # It should be nearby (within a reasonable range)
    for search_col in range(max(0, max_loading_col_idx - 10), 
                           min(df.shape[1], max_loading_col_idx + 10)):
        header = df.iloc[0, search_col]
        
        if isinstance(header, str) and "Contingency (max. loading)" in header:
            # Extract the contingency number
            contingency_number = _extract_last_value(df, search_col)
            if contingency_number is not None:
                try:
                    return int(float(contingency_number))
                except (ValueError, TypeError):
                    continue
    
    return None


def _clean_line_name(line_name):
    """
    Clean line name by removing unnecessary parts.
    
    Args:
        line_name (str): Raw line name
        
    Returns:
        str: Cleaned line name
    """
    if not isinstance(line_name, str):
        return str(line_name)
    
    # Get the last part after backslash
    clean_name = line_name.split('\\')[-1]
    
    # Remove '.ElmLne' suffix
    clean_name = clean_name.replace('.ElmLne', '')
    
    return clean_name


def _extract_base_line_name_from_column_label(col_label: str) -> str:
    """
    Given a CSV column label like 'Line 05 - 06.11', return the base
    DIgSILENT element name 'Line 05 - 06'. If the label does not have
    a trailing '.<index>' part, return it as-is.
    """
    if not isinstance(col_label, str):
        return str(col_label)
    # Column labels look like 'Line 05 - 06.11' or 'Line 05 - 06.2'
    # We strip the last '.<number>' suffix to get the element name.
    if '.' in col_label:
        base, last = col_label.rsplit('.', 1)
        if last.isdigit():
            return base.strip()
    return col_label.strip()


def get_max_loading_summary(csv_file_path='Resultados.csv'):
    """
    Get a summary of the maximum loading across all lines.
    
    Args:
        csv_file_path (str): Path to the CSV file
        
    Returns:
        dict: Dictionary with 'max_loading', 'critical_line', and 'all_lines' keys
    """
    df = parse_contingency_results(csv_file_path)
    
    if df.empty:
        return {
            'max_loading': 0.0,
            'critical_line': 'N/A',
            'all_lines': df
        }
    
    # Get the line with maximum loading
    max_idx = df['Max_Loading_Percent'].idxmax()
    max_loading = df.loc[max_idx, 'Max_Loading_Percent']
    critical_line = df.loc[max_idx, 'Linea']
    
    return {
        'max_loading': max_loading,
        'critical_line': critical_line,
        'all_lines': df
    }


if __name__ == "__main__":
    # Test the parser
    print("Testing CSV parser...")
    result = parse_contingency_results()
    print("\nParsed results:")
    print(result.head(10))
    
    print("\nSummary:")
    summary = get_max_loading_summary()
    print(f"Max loading: {summary['max_loading']}%")
    print(f"Critical line: {summary['critical_line']}")
